// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_magp_mapping_matrix
NumericMatrix cpp_magp_mapping_matrix(const NumericVector& parameters, int q, int mapping_type);
RcppExport SEXP _magp_cpp_magp_mapping_matrix(SEXP parametersSEXP, SEXP qSEXP, SEXP mapping_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type mapping_type(mapping_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_magp_mapping_matrix(parameters, q, mapping_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_magp_covariance
NumericMatrix cpp_magp_covariance(const NumericMatrix& x, const NumericVector& parameters, int q, double tau, int mapping_type);
RcppExport SEXP _magp_cpp_magp_covariance(SEXP xSEXP, SEXP parametersSEXP, SEXP qSEXP, SEXP tauSEXP, SEXP mapping_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type mapping_type(mapping_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_magp_covariance(x, parameters, q, tau, mapping_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_magp_gradient
NumericVector cpp_magp_gradient(const NumericMatrix& x, const NumericVector& parameters, int q, int mapping_type, const NumericMatrix& inverse_covariance, const NumericVector& alpha);
RcppExport SEXP _magp_cpp_magp_gradient(SEXP xSEXP, SEXP parametersSEXP, SEXP qSEXP, SEXP mapping_typeSEXP, SEXP inverse_covarianceSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type mapping_type(mapping_typeSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type inverse_covariance(inverse_covarianceSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_magp_gradient(x, parameters, q, mapping_type, inverse_covariance, alpha));
    return rcpp_result_gen;
END_RCPP
}
// cpp_magp_cross_covariance
NumericMatrix cpp_magp_cross_covariance(const NumericMatrix& training, const NumericMatrix& prediction, const NumericVector& parameters, int q, int mapping_type);
RcppExport SEXP _magp_cpp_magp_cross_covariance(SEXP trainingSEXP, SEXP predictionSEXP, SEXP parametersSEXP, SEXP qSEXP, SEXP mapping_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type training(trainingSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type prediction(predictionSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type mapping_type(mapping_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_magp_cross_covariance(training, prediction, parameters, q, mapping_type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_magp_cpp_magp_mapping_matrix", (DL_FUNC) &_magp_cpp_magp_mapping_matrix, 3},
    {"_magp_cpp_magp_covariance", (DL_FUNC) &_magp_cpp_magp_covariance, 5},
    {"_magp_cpp_magp_gradient", (DL_FUNC) &_magp_cpp_magp_gradient, 6},
    {"_magp_cpp_magp_cross_covariance", (DL_FUNC) &_magp_cpp_magp_cross_covariance, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_magp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
