# Integrated initial-design and Bayesian optimization workflow.

#' Start Bayesian optimization from a generated initial design
#'
#' Constructs a quantitative-sequence initial design, evaluates a user-supplied
#' objective at every initial run, and continues with sequential MaGP Bayesian
#' optimization.
#'
#' @param FUN Objective function. It is called with one named argument for each
#'   input column. It must return one finite numeric value or a list containing
#'   a finite numeric `Score` or `Value` component.
#' @param n_initial Number of runs in the generated initial design.
#' @param q Number of components. Must be at least three.
#' @param model Sequence mapping used by the surrogate: `"2d"` or `"full"`.
#' @param direction Whether `FUN` is being minimized or maximized.
#' @param n_iter Maximum number of sequential evaluations after the initial
#'   design has been evaluated.
#' @param xi Nonnegative exploration offset for expected improvement.
#' @param stop_ei Nonnegative absolute expected-improvement threshold.
#' @param stop_patience Positive whole number of consecutive low-EI evaluations
#'   required for early stopping.
#' @param seed Optional nonnegative whole-number seed. It controls the initial
#'   design, model fitting, sequence sampling, acquisition starts, and any
#'   random values generated by `FUN`, without changing the caller's
#'   random-number state.
#' @param design_control Named list of additional arguments for
#'   [magp_initial_design()], such as `sequence_maxit`, `quantity_maxit`, and
#'   `alignment_maxit`. `n`, `q`, and `seed` are managed by this function.
#' @param fit_control Named list of additional arguments for [magp2d_fit()] or
#'   [magpfull_fit()]. `X`, `y`, and `seed` are managed by this function.
#' @param acquisition_control Named list of additional arguments for
#'   [magp_next_point()]. The fitted model, direction, exploration offset,
#'   reference value, and seed are managed by this function.
#' @param objective_args Named list of fixed additional arguments supplied to
#'   `FUN` after the generated input columns.
#' @param verbose Logical; if `TRUE`, print one line for every initial and
#'   sequential objective evaluation.
#'
#' @details The generated input columns are named `quantity_1` through
#'   `quantity_q` and `sequence_1` through `sequence_q`. The same named-argument
#'   objective interface is used for the initial and sequential evaluations.
#'
#'   Use [magp_bayes_optimize()] instead when completed initial experiments and
#'   their responses are already available.
#'
#' @return An object of class `magp_bayes_opt`. In addition to the components
#'   returned by [magp_bayes_optimize()], it contains `initial_design`,
#'   `initial_response`, `initial_evaluations`, `design_control`, and
#'   `started_from_initial_design`.
#'
#' @examples
#' \donttest{
#' objective <- function(quantity_1, quantity_2, quantity_3,
#'                       sequence_1, sequence_2, sequence_3) {
#'   quantities <- c(quantity_1, quantity_2, quantity_3)
#'   sequence <- c(sequence_1, sequence_2, sequence_3)
#'   -sum((quantities - c(0.2, 0.6, 0.8))^2) -
#'     0.01 * sum((sequence - c(1, 3, 2))^2)
#' }
#' result <- magp_bayes_optimize_from_scratch(
#'   objective,
#'   n_initial = 6,
#'   q = 3,
#'   direction = "maximize",
#'   n_iter = 1,
#'   seed = 1,
#'   design_control = list(
#'     sequence_maxit = 100,
#'     quantity_maxit = 100,
#'     alignment_maxit = 100
#'   ),
#'   fit_control = list(maxeval = 100),
#'   acquisition_control = list(n_starts = 2, maxit = 20)
#' )
#' result$best_point
#' result$best_value
#' }
#'
#' @export
magp_bayes_optimize_from_scratch <- function(
    FUN, n_initial, q, model = c("2d", "full"),
    direction = c("minimize", "maximize"), n_iter = 10L,
    xi = 0, stop_ei = 0, stop_patience = 3L, seed = NULL,
    design_control = list(), fit_control = list(),
    acquisition_control = list(), objective_args = list(),
    verbose = TRUE) {
  call <- match.call()
  if (!is.function(FUN)) {
    stop("FUN must be a function", call. = FALSE)
  }
  model <- match.arg(model)
  direction <- .magp_match_direction(direction)
  .magp2d_validate_scalar(
    n_initial, "n_initial", lower = 2, integer = TRUE
  )
  .magp2d_validate_scalar(q, "q", lower = 3, integer = TRUE)
  .magp2d_validate_scalar(n_iter, "n_iter", lower = 0, integer = TRUE)
  .magp2d_validate_scalar(xi, "xi", lower = 0)
  .magp2d_validate_scalar(stop_ei, "stop_ei", lower = 0)
  .magp2d_validate_scalar(
    stop_patience, "stop_patience", lower = 1, integer = TRUE
  )
  .magp2d_validate_scalar(
    seed, "seed", lower = 0, upper = .Machine$integer.max,
    integer = TRUE, allow_null = TRUE
  )
  if (!is.logical(verbose) || length(verbose) != 1L || is.na(verbose)) {
    stop("verbose must be TRUE or FALSE", call. = FALSE)
  }

  design_allowed <- setdiff(
    names(formals(magp_initial_design)),
    c("n", "q", "seed")
  )
  design_control <- .magp_named_control(
    design_control,
    "design_control",
    design_allowed
  )
  fit_function <- if (identical(model, "2d")) magp2d_fit else magpfull_fit
  fit_control <- .magp_named_control(
    fit_control,
    "fit_control",
    setdiff(names(formals(fit_function)), c("X", "y", "seed"))
  )
  acquisition_control <- .magp_named_control(
    acquisition_control,
    "acquisition_control",
    setdiff(
      names(formals(magp_next_point)),
      c("object", "direction", "xi", "best", "seed")
    )
  )
  objective_args <- .magp_named_control(
    objective_args,
    "objective_args",
    names(objective_args)
  )

  input_names <- c(
    paste0("quantity_", seq_len(as.integer(q))),
    paste0("sequence_", seq_len(as.integer(q)))
  )
  duplicated_arguments <- intersect(input_names, names(objective_args))
  if (length(duplicated_arguments)) {
    stop(
      "objective_args duplicates input name(s): ",
      paste(duplicated_arguments, collapse = ", "),
      call. = FALSE
    )
  }

  n_initial <- as.integer(n_initial)
  q <- as.integer(q)
  output <- .magp_with_local_seed(seed, {
    initial_design <- do.call(
      magp_initial_design,
      c(
        list(n = n_initial, q = q, seed = seed),
        design_control
      )
    )

    initial_response <- numeric(n_initial)
    for (i in seq_len(n_initial)) {
      point <- as.data.frame(
        initial_design$design[i, , drop = FALSE],
        check.names = FALSE
      )
      initial_response[[i]] <- .magp_bo_evaluate(
        FUN,
        point,
        objective_args,
        paste0("initial run ", i)
      )
      if (verbose) {
        cat(
          "initial run", i,
          "value", format(initial_response[[i]], digits = 6),
          "\n"
        )
      }
    }

    result <- magp_bayes_optimize(
      FUN = FUN,
      X = initial_design$design,
      y = initial_response,
      model = model,
      direction = direction,
      n_iter = n_iter,
      xi = xi,
      stop_ei = stop_ei,
      stop_patience = stop_patience,
      seed = .magp_seed_offset(seed, 10000L),
      fit_control = fit_control,
      acquisition_control = acquisition_control,
      objective_args = objective_args,
      verbose = verbose
    )
    result$call <- call
    result$initial_design <- initial_design
    result$initial_response <- initial_response
    result$initial_evaluations <- n_initial
    result$design_control <- design_control
    result$started_from_initial_design <- TRUE
    result
  })
  output
}
