# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_magp_mapping_matrix <- function(parameters, q, mapping_type) {
    .Call(`_magp_cpp_magp_mapping_matrix`, parameters, q, mapping_type)
}

cpp_magp_covariance <- function(x, parameters, q, tau, mapping_type) {
    .Call(`_magp_cpp_magp_covariance`, x, parameters, q, tau, mapping_type)
}

cpp_magp_gradient <- function(x, parameters, q, mapping_type, inverse_covariance, alpha) {
    .Call(`_magp_cpp_magp_gradient`, x, parameters, q, mapping_type, inverse_covariance, alpha)
}

cpp_magp_cross_covariance <- function(training, prediction, parameters, q, mapping_type) {
    .Call(`_magp_cpp_magp_cross_covariance`, training, prediction, parameters, q, mapping_type)
}

magp_sfta_search_cpp <- function(orders, pair_weight, space_weight, p, maxit, ncalibrate, nrounds) {
    .Call(`_magp_magp_sfta_search_cpp`, orders, pair_weight, space_weight, p, maxit, ncalibrate, nrounds)
}

